# Generated by Django 5.2.6 on 2025-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
