# Generated by Django 5.2.6 on 2025-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_excelfile_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('reg_no', 'course_code', 'semester')},
        ),
    ]
