# Generated by Django 5.2.6 on 2025-10-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_studentgrade_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='reg_no',
            field=models.CharField(max_length=20),
        ),
    ]
