# Generated by Django 5.2.6 on 2025-10-03 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_excelfile_user_id_excelfile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excelfile',
            unique_together={('user', 'course_code', 'file_name')},
        ),
    ]
