# Generated by Django 5.2.6 on 2025-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_internalexcelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internalexcelfile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internalexcelfile',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
