# Generated by Django 5.2.6 on 2025-10-04 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_excelfile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('reg_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('total', models.FloatField()),
                ('percentage', models.FloatField()),
            ],
            options={
                'unique_together': {('exam_name', 'course_code', 'reg_no')},
            },
        ),
        migrations.CreateModel(
            name='CollegeExamExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.BinaryField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_code', 'file_name')},
            },
        ),
    ]
