# Generated by Django 5.2.6 on 2025-10-05 05:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_collegeexam_user_alter_collegeexamexcel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collegeexam',
            unique_together={('exam_name', 'course_code', 'reg_no', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('reg_no', 'course_code', 'semester', 'user')},
        ),
    ]
