# Generated by Django 5.2.6 on 2025-10-05 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_mergefile_sendmergefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmergefile',
            old_name='course_code',
            new_name='department',
        ),
        migrations.AlterUniqueTogether(
            name='mergefile',
            unique_together={('user', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sendmergefile',
            unique_together={('user', 'department', 'file_name')},
        ),
        migrations.RemoveField(
            model_name='mergefile',
            name='course_code',
        ),
    ]
