# Generated by Django 5.2.6 on 2025-10-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_rename_course_code_sendmergefile_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mergefile',
            unique_together=set(),
        ),
    ]
