# Generated by Django 5.2.6 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_alter_department_options_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeexam',
            name='college_log',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeexam',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='semester_log',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
