# Generated by Django 5.2.6 on 2025-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_collegeexam_college_log_collegeexam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeexam',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
