# Generated by Django 5.2.6 on 2025-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_collegeexam_status_alter_studentgrade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeexam',
            name='reg_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='reg_no',
            field=models.IntegerField(),
        ),
    ]
