# Generated by Django 5.2.6 on 2025-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_collegeexam_reg_no_alter_studentgrade_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeexam',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegeexam',
            name='total',
            field=models.IntegerField(),
        ),
    ]
