# Generated by Django 5.2.6 on 2025-11-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_sendinternalfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendInternalFile',
        ),
    ]
